#!/usr/bin/env python3
"""Verify backup outputs, portal manifest, and researchData.js are in sync."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

from sync_portal_research import (  # noqa: E402
    BACKUP,
    MANIFEST_PATH,
    RESEARCH_JS,
    build_manifest,
)

REQUIRED_FIGURES = [
    "patient-doctor-portal/research-figures/pcos-top-coefficients.png",
    "patient-doctor-portal/research-figures/pcos-prediction-distribution.png",
    "patient-doctor-portal/research-figures/pcos-vs-endo-features.png",
    "patient-doctor-portal/research-figures/pcos-vs-endo-coefficients.png",
    "patient-doctor-portal/research-figures/scrna/scrna_deep_summary.json",
    "patient-doctor-portal/research-figures/scrna/umap_endometrium.png",
    "patient-doctor-portal/research-figures/scrna/umap_Mc26.png",
    "patient-doctor-portal/research-figures/scrna/marker_heatmap_endometrium.png",
    "patient-doctor-portal/research-figures/scrna/marker_heatmap_Mc26.png",
]


def _extract_export(js: str, name: str) -> dict | list:
    pattern = rf"export const {name}\s*=\s*(\{{|\[)"
    m = re.search(pattern, js)
    if not m:
        raise ValueError(f"Missing export {name} in researchData.js")
    start = m.start(1)
    opener = js[start]
    closer = "}" if opener == "{" else "]"
    depth = 0
    i = start
    while i < len(js):
        c = js[i]
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                chunk = js[start : i + 1]
                return json.loads(chunk)
        i += 1
    raise ValueError(f"Unterminated export {name}")


def verify() -> None:
    repo = SCRIPTS.parents[1]
    errors: list[str] = []

    for rel in REQUIRED_FIGURES:
        if not (repo / rel).is_file():
            errors.append(f"Missing figure: {rel}")

    if not MANIFEST_PATH.is_file():
        errors.append("Missing backup/portal_sync_manifest.json — run sync_portal_research.py")
    if not RESEARCH_JS.is_file():
        errors.append("Missing patient-doctor-portal/js/researchData.js")

    if errors:
        raise SystemExit("VERIFY FAILED:\n" + "\n".join(errors))

    expected = build_manifest()
    saved = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    for key in (
        "pcosCohort",
        "pcosVsEndo",
        "scrnaInventory",
        "pcosTopCorrelations",
        "pcosModelCoefPositive",
    ):
        if saved.get(key) != expected.get(key):
            errors.append(f"Manifest stale for {key} (re-run sync)")

    js = RESEARCH_JS.read_text(encoding="utf-8")
    if "AUTO-GENERATED by backup/scripts/sync_portal_research.py" not in js:
        errors.append("researchData.js is not auto-generated (hand-edited?)")

    js_cohort = _extract_export(js, "PCOS_COHORT")
    if js_cohort != saved["pcosCohort"]:
        errors.append("PCOS_COHORT in researchData.js does not match manifest")

    js_endo = _extract_export(js, "PCOS_VS_ENDO")
    if js_endo != saved["pcosVsEndo"]:
        errors.append("PCOS_VS_ENDO in researchData.js does not match manifest")

    js_scrna = _extract_export(js, "SCRNA_INVENTORY")
    exp_scrna = {k: v for k, v in saved["scrnaInventory"].items() if k != "totalCells"}
    if js_scrna != exp_scrna:
        errors.append("SCRNA_INVENTORY in researchData.js does not match manifest")

    scrna_manifest = json.loads(
        (repo / "patient-doctor-portal/research-figures/scrna/scrna_deep_summary.json").read_text()
    )
    if not scrna_manifest.get("available") or not scrna_manifest.get("analyses"):
        errors.append("scrna_deep_summary.json has no analyses")

    if errors:
        raise SystemExit("VERIFY FAILED:\n" + "\n".join(errors))

    print("Portal sync verification passed.")
    print(f"  PCOS n={saved['pcosCohort']['n']}  ROC-AUC={saved['pcosCohort']['cvRocAuc']}")
    print(
        f"  Compare {saved['pcosVsEndo']['pcosN']} vs {saved['pcosVsEndo']['endoN']}  "
        f"AUC={saved['pcosVsEndo']['differentiationAuc']}"
    )
    print(f"  scRNA cells={saved['scrnaInventory']['totalCells']:,}")


def main() -> None:
    verify()


if __name__ == "__main__":
    main()
